[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.css'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/theme.rasi'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.discord]
input_path = '~/.config/matugen/templates/discord.css'
output_path = '~/.config/vesktop/themes/matugen.css'

[templates.spotify]
input_path = '~/.config/matugen/templates/spotify.ini'
output_path = '~/.config/spicetify/Themes/Matugen/color.ini'
# post_hook = 'spicetify watch -s 2>&1 | sed "/Reloaded Spotify/q"'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs'

[templates.wlogout]
input_path = '~/.config/matugen/templates/wleave.css'
output_path = '~/.config/wleave/colors.css'

[templates.zed]
input_path = '~/.config/matugen/templates/zed.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.cava]
input_path = '~/.config/matugen/templates/cava.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

# [templates.quickshell]
# input_path = '~/.config/matugen/templates/quickshell.json'
# output_path = '~/.config/quickshell/colors.json'
